### ISSUE TITLE
Issue with same vulnerability reported on different ports for multiple systems

### ISSUE THREAD

**Issue by ashishpujari** [nccgroup/lapith#3]
Hi,
Let me start by saying this tool is really great.
I noticed that when I merged multiple scan files and if a vulnerability is present on different ports for multiple systems it messes with the Output tab.

**Comment by lllama** [comment]
Can you explain "messes with"? It should display one of the result files in the output tab and then a "diff" tab that will show the changes between the second result and the first.

**Comment by ashishpujari** [comment]
Hi sorry for the delayed response. I did not notice the extra diff tab. Please ignore my above comment. This a great and very helpful tool.
However there was one thing that I wanted to point out that in case we have to import multiple scan reports to import, containing the same set of systems, the tool duplicates the IP of the machine.
I was able to fix this in my local copy, by making some code changes. It is just something that I observed.

**Comment by lllama** [comment]
I'll close this issue and add the removal of duplicate IP addresses as an enhancement. I'll probably keep the dups in the diff tab, as they will have come from different scans but may have different results.
