### ISSUE TITLE
Issues for different hosts with different details are represented incorrectly:

### ISSUE THREAD

**Issue by truekonrads** [nccgroup/lapith#5]
Dear @lllama,
When there are two or more hosts that have the same issue ,but the details are different - e.g. list of enumerated users is different, then details are incorrectly displayed. The same, identical entry is for each item with same plugin id (e.g. 10107)
![image](https://cloud.githubusercontent.com/assets/1421150/3839014/b50fa9dc-1e0b-11e4-8cef-dcdc212f5b90.png)

I would expect that there is only one entry for each plugin ID and in the "Output" tab there would be a per-IP/port breakdown. Optionally, there could be a new tab which displays the breakdown as a table.

Nessus file was produced with "Nessus-5.2.7"

**Comment by lllama** [comment]
The 'Diffs' tab should contain the differences. Not the prettiest of GUIs, but the tab's presence lets you know that there are different results. I.e. if it's not there then all of the output is the same.
